# Generated by Django 5.0.6 on 2024-06-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rchat', '0003_soundtracks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoundTracks',
        ),
    ]
