# Generated by Django 5.0.6 on 2024-06-13 17:50

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rchat', '0006_alter_privatechat_chat_name_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='chat_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
