# Generated by Django 5.0.6 on 2024-06-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rchat', '0007_alter_privatechat_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
